amcl:
  ros__parameters:
    base_frame_id: "base_link"
    global_frame_id: "map_amcl"
    odom_frame_id: "odom_combined"
    scan_topic: scan_unified
    map_topic: map_amcl

    # partical
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 0.99
    resample_interval: 1

    # recover
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    save_pose_rate: 0.5
    bond_heartbeat_period: 0.1

    # pose
    tf_broadcast: true
    transform_tolerance: 1.0

    # motion model
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.3
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.3
    alpha5: 0.1

    update_min_a: 0.1
    update_min_d: 0.1

    # sensor
    laser_model_type: "beam"
    laser_max_range: 40.0
    laser_min_range: 0.1
    max_beams: 524
    laser_likelihood_max_dist: 2.0

    z_hit: 0.5
    z_rand: 0.005
    z_short: 0.05
    z_max: 0.05
    lambda_short: 0.1
    sigma_hit: 0.2

    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.98
    beam_skip_threshold: 0.3
# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
# map_server:
#   ros__parameters:
#     yaml_filename: ""
